services:
  app:
    image: goods-service
    build: 
      context: .
      dockerfile: GoodsService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__DefaultConnection=Server=sql;User=sa;Password=Password123@!!!;MultipleActiveResultSets=true;Encrypt=True;TrustServerCertificate=True;
      - DatabaseType=SqlServer
    ports:
      - "8080:8080"
    depends_on:
      - sql
  sql:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_USER: "sa"
      SA_PASSWORD: "Password123@!!!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - /var/opt/mssql